### PR TITLE
Bump to 0.1.1

### PR DESCRIPTION
**Pull request by LionOps**

### CODE REVIEW

**Comment by thomasw** [comment]
:+1:

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by Hkly** [comment]
:+1:

**Comment by LionOps** [comment]
Going to rebase this so the history makes sense.

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Pull request merged**
